/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_doit_openglesprac_egl_NativeEglRender */

#ifndef _Included_com_doit_openglesprac_egl_NativeEglRender
#define _Included_com_doit_openglesprac_egl_NativeEglRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_doit_openglesprac_egl_NativeEglRender
 * Method:    native_EglRenderInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_doit_openglesprac_egl_NativeEglRender_native_1EglRenderInit
  (JNIEnv *, jobject);

/*
 * Class:     com_doit_openglesprac_egl_NativeEglRender
 * Method:    native_EglRenderSetImageData
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_doit_openglesprac_egl_NativeEglRender_native_1EglRenderSetImageData
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_doit_openglesprac_egl_NativeEglRender
 * Method:    native_EglRenderSetIntParams
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_doit_openglesprac_egl_NativeEglRender_native_1EglRenderSetIntParams
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_doit_openglesprac_egl_NativeEglRender
 * Method:    native_EglRenderDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_doit_openglesprac_egl_NativeEglRender_native_1EglRenderDraw
  (JNIEnv *, jobject);

/*
 * Class:     com_doit_openglesprac_egl_NativeEglRender
 * Method:    native_EglRenderUnInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_doit_openglesprac_egl_NativeEglRender_native_1EglRenderUnInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
